{% set name = "ptpython" %}
{% set version = "3.0.29" %}
{% set file_ext = "tar.gz" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: {{ name }} -{{ version }}.{{ file_ext }}
  url: https://pypi.python.org/packages/source/p/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}

build:
  number: 0
  entry_points:
    - ptpython = ptpython.entry_points.run_ptpython:run
    - ptipython = ptpython.entry_points.run_ptipython:run
    - ptpython3 = ptpython.entry_points.run_ptpython:run
    - ptipython3 = ptpython.entry_points.run_ptipython:run
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - docopt
    - appdirs
    # These limits tend to change with updates to ptpython (particularly
    # the prompt_toolkit which is constantly breaking things. Check
    # these if you modify versions. Also update meta.yaml for geocal
    # and afids-development-tools
    - jedi >=0.16.0
    - prompt_toolkit >=3.0.43,<3.1.0
    - pygments
    - black
  run:
    - python
    - docopt
    - appdirs
    - jedi >=0.16.0
    - prompt_toolkit >=3.0.43,<3.1.0
    - pygments
    - black

test:
  imports:
    - ptpython
    - ptpython.contrib
    - ptpython.entry_points
  commands:
    - ptpython --help
    - ptipython --help
    - ptpython3 --help
    - ptipython3 --help

about:
  home: https://github.com/jonathanslenders/ptpython
  license: UNKNOWN
  license_family: OTHER
  license_file: ''
  summary: Python REPL build on top of prompt_toolkit
  description: UNKNOWN
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
