{% set name = "vicar-gdalplugin" %}
{% set version = "1.12" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: https://github.com/Cartography-jpl/{{ name }}.git
  git_rev: {{ version }}

build:
#  number: 0
# Update libgdal
#  number: 1
# Stand alone public version
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
    - perl
    - patch
    - make
    - m4
    - pkg-config 
  host:
    - vicar-rtl
    - libgdal {{ libgdal }}
    - boost
  run:
    - vicar-rtl 
    - libgdal {{ libgdal }}
    - boost

about:
  license: BSD
  license_file: ../LICENSE
  summary: This is a plugin for GDAL to support VICAR files

