{% set name = "afids-data" %}
{% set version = "1.11" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: https://github.com/Cartography-jpl/{{ name }}.git
  git_rev: {{ version }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}  
    # Don't really need cxx or fortran, but configure checks for this and
    # fails if it doesn't find it
    - {{ compiler('cxx') }}  
    - {{ compiler('fortran') }}
    - git
    - perl
    - patch
    - m4
    - make
  host:
  run:

about:
  license: BSD
  license_file: ../LICENSE
  summary: This is AFIDS support data

