{% set name = "geocal" %}
{% set version = "20240916" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - git_url: https://github.com/Cartography-jpl/{{ name }}.git
    git_rev: {{ version }}
    folder: geocal
    # Spice is a little complicated, because of the licensing. We can download
    # and link against this, and then distribute the package. But we can't redistribute
    # the spice library. So we go ahead and download when we build, and then use the
    # packages that we have built without including the libraries directly in conda
  - url: https://naif.jpl.nasa.gov/pub/naif/toolkit//C/PC_Linux_GCC_64bit/packages/cspice.tar.Z
    folder: cspice
    

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}  
    - {{ compiler('cxx') }}  
    - {{ compiler('fortran') }}
    - git
    - perl
    - patch
    - make
    - m4
    - pkg-config 
  host:
    - conda
    - blas
    - scipy
    - matplotlib
    - sphinx
    - pytest
    - pytest-xdist
    - pytest-cov
    - ipython
    - jupyter
    # Note this library can be a bit limiting in what else can be installed.
    # We can live without this, the sba takes advantage of this library if
    # available, but it only matters for large systems. Everything works without
    # having umfpack available.
    - scikit-umfpack
    - seaborn
    - pandas
    - numpydoc
    - jsonpickle
    - tabulate
    - future
    - six
    - docopt
    - appdirs
    # These limits come from ptpython
    - jedi >=0.16.0
    - prompt_toolkit >=3.0.18,<3.1.0
    - pygments
    - black
    - h5py
    - gdal {{ gdal }}
    - libgdal {{ libgdal }}
    - boost
    - hdf5 {{ hdf5 }}
    - hdfeos5
    - gsl
    - afids-carto
    - pkgconfig
    - doxygen
    # Swig 4.0 breaks a few things. Probably minor stuff to fix,
    # but until then we'll stick to the older version
    - swig<4.0.0
    - ncurses
    - fftw
    - ptpython
    - vicar-rtl
    - vicar-gdalplugin
    - afids-data
    - spice
    - libblitz
    - graphviz
    - pynitf
    # This doesn't build now, and I'm not sure we actually need this. For now just
    # use opencv, and we can come back to this if needed
    # Not strictly required, but useful
    #- opencv-nonfree
    - opencv
    # Only needed if we are supporting ISIS
    - rclone
  run:
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - conda
    - libnetcdf
    - gsl
    - blas
    - scipy
    - matplotlib
    - sphinx
    - pytest
    - pytest-xdist
    - pytest-cov
    - ipython
    - jupyter
    # Note this library can be a bit limiting in what else can be installed.
    # We can live without this, the sba takes advantage of this library if
    # available, but it only matters for large systems. Everything works without
    # having umfpack available.
    - scikit-umfpack
    - seaborn
    - pandas
    - numpydoc
    - jsonpickle
    - tabulate
    - future
    - six
    - docopt
    # These limits come from ptpython
    - jedi >=0.16.0
    - prompt_toolkit >=3.0.11,<3.1.0
    - pygments
    - black
    - h5py
    - gdal
    - libgdal
    - boost
    - hdf5 {{ hdf5 }}
    - hdfeos5
    - afids-carto
    - pkgconfig
    - doxygen
    - swig
    - ncurses
    - fftw
    - ptpython
    - vicar-rtl
    - vicar-gdalplugin
    - afids-data
    # Not actually needed to run, we already link the .a file in.
    #- spice
    - libblitz
    - graphviz
    - pynitf
    # This doesn't build now, and I'm not sure we actually need this. For now just
    # use opencv, and we can come back to this if needed
    # Not strictly required, but useful
    #- opencv-nonfree
    - opencv
    # Only needed if we are supporting ISIS
    - rclone
    
about:
  home: https://github.jpl.nasa.gov/Cartography/geocal
  license: BSD
  license_file: ../LICENSE
  summary: This is a the GeoCal package
