{% set name = "emit" %}
{% set version = "1.6.19" %}
{% set file_ext = "tar.bz2" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
# We have a build step that automatically generates this tar file
# Would be nice to download from github, but we have permission problems for
# doing that 
  url: ../src/{{ name }}-{{ version }}.{{ file_ext }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}  
    - {{ compiler('cxx') }}  
    - {{ compiler('fortran') }}  
    - perl
    - patch
    - make
    - m4
    - pkg-config 
  host:
    - geocal
    - h5netcdf
    - afids-development-tools
    - afids-data
    - python {{ python }}
    - pip
  run:
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - geocal
    - h5netcdf
    - afids-development-tools
    - afids-data
    - python {{ python }}
    - pip
    
about:
  home: https://github.com/emit-sds/emit-sds-l1b-geo
  license: Apache License Version 2.0
  license_file: ../LICENSE
  summary: This is a the emit-l1b-geo package
