{% set name = "pynitf" %}
{% set version = "1.14" %}
# TODO See tests turned off below, should turn back on for next version

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/Cartography-jpl/{{ name }}.git
  git_rev: {{ version }}

build:
  number: 0
  noarch: generic
  script: "python -m pip install . --no-deps --ignore-installed --no-cache-dir --no-index -vvv "

requirements:
  build:
    - git
  host:
    - pip
    - six
    - numpy {{ numpy }}
    - python {{ python }}
    - docopt
    - pytest-runner
    - jsonpickle
    - h5py
  run:
    - {{ pin_compatible('numpy') }}
    - python {{ python }}
    - docopt
    - jsonpickle
    - h5py

# Short term turn these off. We have added unit tests that require git.
# Should have a handle for this in pynitf to skip if not available, but
# for now just skip the tests so we can build the package
#test:
#  requires:
#    - pytest
#  source_files:
#    - tests
#  commands:
#    pytest tests

about:
  home: https://github.jpl.nasa.gov/Cartography/pynitf
  license: BSD
  license_file: ../LICENSE
  summary: This is a python module used to read and write NITF 2.1 files.

