{% set name = "gnuplot" %}
{% set version = "6.0.1" %}
{% set file_ext = "tar.gz" %}

package:
  name: '{{ name|lower }}'
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/gnuplot/gnuplot-{{ version }}.{{ file_ext }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - perl
    - patch
    - make
    - m4
    - pkg-config
  host:
    - pkgconfig
    - ncurses
    - readline
    - libgd
    - cairo
    - pango
    # Not a direct dependency, but we get a conflict with gdal. So
    # hold this version fixed
    - libuuid {{ libuuid }}
    - glib
    - libiconv
    - iconv
    - xorg-libxext
    - xorg-libx11
    - xorg-libxrender
    - xorg-libxau
    - xorg-libsm
    - xorg-libice
    - xorg-libxdmcp
  run:
    - ncurses
    - readline
    - libgd
    - cairo
    - pango
    - glib
    - libiconv
    - xorg-libxext
    - xorg-libx11
    - xorg-libxrender
    - xorg-libxau
    - xorg-libsm
    - xorg-libice
    - xorg-libxdmcp
