{% set name = "joe-editor" %}
{% set version = "4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/{{ name }}/joe-{{ version }}.tar.gz
  patches:
    - joe-conda.patch

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }} 
    - patch
    - make
  host:
    - ncurses
  run:
    - ncurses


