# Note that this doesn't 100% test cleanly. But enough of this is working
# that it is worth making a package for this.
{% set name = "afids" %}
{% set version = "1.26" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - git_url: https://github.com/Cartography-jpl/{{ name }}.git
    git_rev: {{ version }}
    folder: afids
    # Spice is a little complicated, because of the licensing. We can download
    # and link against this, and then distribute the package. But we can't redistribute
    # the spice library. So we go ahead and download when we build, and then use the
    # packages that we have built without including the libraries directly in conda
  - url: https://naif.jpl.nasa.gov/pub/naif/toolkit//C/PC_Linux_GCC_64bit/packages/cspice.tar.Z
    folder: cspice

build:
#  number: 1
# Update libgdal
#  number: 2
#  number: 3
# Use new stand alone version of afids
  number: 5


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - git
    - perl
    - patch
    - make
    - m4
    - pkg-config
  host:
    - afids-data
    # This should migrate to conda_build_config.yaml, but for now
    # just force this here so we can build
    - vicar
    - gdal {{ gdal }}
    - libgdal {{ libgdal }}
    - boost
    - afids-carto
    - blas
    - vicar-rtl
    - tix
    - itcl
    - tk
    - gsl
    - hdfeos2
    - geotiff
    - fftw
    - vicar-gdalplugin
    - afids-xvd
    - gnuplot
  run:
    - afids-data
    - vicar 
    - gdal {{ gdal }}
    - libgdal {{ libgdal }}
    - boost
    - afids-carto
    - blas
    - vicar-rtl
    - tix
    - itcl
    - tk
    - gsl
    - hdfeos2
    - geotiff
    - fftw
    - vicar-gdalplugin
    - gnuplot

about:
  license: BSD
  license_file: ../LICENSE
  summary: This is AFIDS.

