{% set name = "vicar-rtl" %}
{% set version = "1.10" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: https://github.com/Cartography-jpl/{{ name }}.git
  git_rev: {{ version }}

build:
  number: 2
    
requirements:
  build:
    - {{ compiler('c') }}  
    - {{ compiler('cxx') }}  
    - {{ compiler('fortran') }}
    - git
    - perl
    - patch
    - make
    - pkg-config 
  host:
    - ncurses
  run:
    - ncurses

about:
  license: BSD
  license_file: ../LICENSE
  summary: The VICAR run time library

